project: 
  type: website
  output-dir: docs

website:
  title: "Asmith Joseph Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/Asmithj/AsmithJoseph-MADA-portfolio      
format:
  html:
    theme: cosmo
    highlight: monokai
    css: styles.css
    toc: FALSE